import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Sidenavbar from "../components/Sidenavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-900">
        <Header />
        
        <div className="grid grid-cols-1 md:grid-cols-12 max-w-screen-2xl mx-auto w-full">
          <div className="hidden md:block md:col-span-3">
            <Sidenavbar />
          </div>
          <main className="col-span-1 md:col-span-9 px-4 md:px-8">
            {children}
          </main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
